local f=function(name, en, ru)
	if RUWOW_EnableCombatLog then
		setglobal(name, ru)
	else
		setglobal(name, en)
	end
end
RUWOW_LocalizeCombatLog=function()
f("ABSORB_TRAILER"," (%d absorbed)"," (%d поглощено)");
f("AURAADDEDOTHERHARMFUL","%s is afflicted by %s.","%s поражен(а) %s.");
f("AURAADDEDOTHERHELPFUL","%s gains %s.","%s получил(а) %s.");
f("AURAADDEDSELFHARMFUL","You are afflicted by %s.","Вы поражены %s.");
f("AURAADDEDSELFHELPFUL","You gain %s.","Вы получили %s.");
f("AURACHANGEDOTHER","%s replaces %s with %s.","%s заменил(а) %s на %s.");
f("AURACHANGEDSELF","You replace %s with %s.","Вы заменили %s на %s.");
f("AURADISPELOTHER","%s's %s is removed.","Наложенное %s колдовство %s снято.");
f("AURADISPELSELF","Your %s is removed.","%s снято");
f("AURAREMOVEDOTHER","%s fades from %s.","%s наложенное на %s закончилось.");
f("AURAREMOVEDSELF","%s fades from you.","Действие %s закончилось.");
f("BLOCK_TRAILER"," (%d blocked)"," (%d блокировано)");
f("COMBATHITCRITOTHEROTHER","%s crits %s for %d.","%s нанес %s критический удар - %d.");
f("COMBATHITCRITOTHERSELF","%s crits you for %d.","%s нанес вам критический удар - %d.");
f("COMBATHITCRITSELFOTHER","You crit %s for %d.","Вы нанесли %s критический удар - %d.");
f("COMBATHITOTHEROTHER","%s hits %s for %d.","%s нанес %s урон - %d.");
f("COMBATHITOTHERSELF","%s hits you for %d.","%s нанес вам урон - %d.");
f("COMBATHITSELFOTHER","You hit %s for %d.","Вы нанесли %s урон - %d.");
f("COMBATLOG_DISHONORGAIN","%s dies, dishonorable kill.","%s умер, позорное убийство.");
f("COMBATLOG_HONORGAIN","%s dies, honorable kill Rank: %s (Estimated Honor Points: %d)","%s умер, почётное убийство.(Ранг: %s)");
f("COMBATLOG_XPGAIN","%s gains %d experience.","%s получил(а) %d опыта.");
f("COMBATLOG_XPGAIN_EXHAUSTION1","%s dies, you gain %d experience. (%s exp %s bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION1_GROUP","%s dies, you gain %d experience. (%s exp %s bonus, +%d group bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус, +%d групповой бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION1_RAID","%s dies, you gain %d experience. (%s exp %s bonus, -%d raid penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус, -%d рейд-штраф)");
f("COMBATLOG_XPGAIN_EXHAUSTION2","%s dies, you gain %d experience. (%s exp %s bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION2_GROUP","%s dies, you gain %d experience. (%s exp %s bonus, +%d group bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус, +%d групповой бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION2_RAID","%s dies, you gain %d experience. (%s exp %s bonus, -%d raid penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s бонус, -%d рейд-штраф)");
f("COMBATLOG_XPGAIN_EXHAUSTION4","%s dies, you gain %d experience. (%s exp %s penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф)");
f("COMBATLOG_XPGAIN_EXHAUSTION4_GROUP","%s dies, you gain %d experience. (%s exp %s penalty, +%d group bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф, +%d групповой бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION4_RAID","%s dies, you gain %d experience. (%s exp %s penalty, -%d raid penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф, -%d рейд-штраф)");
f("COMBATLOG_XPGAIN_EXHAUSTION5","%s dies, you gain %d experience. (%s exp %s penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф)");
f("COMBATLOG_XPGAIN_EXHAUSTION5_GROUP","%s dies, you gain %d experience. (%s exp %s penalty, +%d group bonus)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф, +%d групповой бонус)");
f("COMBATLOG_XPGAIN_EXHAUSTION5_RAID","%s dies, you gain %d experience. (%s exp %s penalty, -%d raid penalty)","%s умер(ла), вы получили %d очков опыта. (%s опыт %s штраф, -%d рейд-штраф)");
f("COMBATLOG_XPGAIN_FIRSTPERSON","%s dies, you gain %d experience.","%s умер(ла), вы получили %d очков опыта.");
f("COMBATLOG_XPGAIN_FIRSTPERSON_GROUP","%s dies, you gain %d experience. (+%d group bonus)","%s умер(ла), вы получили %d очков опыта. (+%d групповой бонус)");
f("COMBATLOG_XPGAIN_FIRSTPERSON_RAID","%s dies, you gain %d experience. (-%d raid penalty)","%s умер(ла), вы получили %d очков опыта. (-%d рейд-штраф)");
f("COMBATLOG_XPGAIN_FIRSTPERSON_UNNAMED","You gain %d experience.","Вы получили %d очков опыта.");
f("COMBATLOG_XPGAIN_FIRSTPERSON_UNNAMED_GROUP","You gain %d experience. (+%d group bonus)","Вы получили %d очков опыта. (+%d групповой бонус)");
f("COMBATLOG_XPGAIN_FIRSTPERSON_UNNAMED_RAID","You gain %d experience. (-%d raid penalty)","Вы получили %d очков опыта. (-%d рейд-штраф)");
f("COMBATLOG_XPLOSS_FIRSTPERSON_UNNAMED","You lose %d experience.","Вы потеряли %d очков опыта.");
f("CRUSHING_TRAILER"," (crushing)"," (разрушительный)");
f("GLANCING_TRAILER"," (glancing)"," (скользящий)");
f("HEALEDCRITOTHEROTHER","%s's %s critically heals %s for %d.","%s с помощью %s критически вылечил %s на %d.");
f("HEALEDCRITOTHERSELF","%s's %s critically heals you for %d.","%s с помощью %s критически вылечил вас на %d.");
f("HEALEDCRITSELFOTHER","Your %s critically heals %s for %d.","С помощью %s вы критически вылечили %s на %d.");
f("HEALEDCRITSELFSELF","Your %s critically heals you for %d.","С помощью %s вы критически вылечили себя на %d.");
f("HEALEDOTHEROTHER","%s's %s heals %s for %d.","%s с помощью %s вылечил %s на %d.");
f("HEALEDOTHERSELF","%s's %s heals you for %d.","%s с помощью %s вылечил вас на %d.");
f("HEALEDSELFOTHER","Your %s heals %s for %d.","С помощью %s вы вылечили %s на %d.");
f("HEALEDSELFSELF","Your %s heals you for %d.","С помощью %s вы вылечили себя на %d.");
f("MISSEDOTHEROTHER","%s misses %s.","%s промахнулся(ась) по %s.");
f("MISSEDOTHERSELF","%s misses you.","%s промахнулся(ась) по вам.");
f("MISSEDSELFOTHER","You miss %s.","Вы промахнулись по %s.");
f("OPEN_LOCK_OTHER","%s performs %s on %s.","%s применил(а) %s на %s.");
f("OPEN_LOCK_SELF","You perform %s on %s.","Вы применили %s на %s.");
f("PERIODICAURADAMAGEOTHEROTHER","%s suffers %d %s damage from %s's %s.","%s получил(а) %d %s урона от используемого %s - %s.");
f("PERIODICAURADAMAGEOTHERSELF","You suffer %d %s damage from %s's %s.","Вы получили %d %s урона от используемого %s - %s.");
f("PERIODICAURADAMAGESELFOTHER","%s suffers %d %s damage from your %s.","%s получил(а) %d %s урона от вашего %s.");
f("PERIODICAURADAMAGESELFSELF","You suffer %d %s damage from your %s.","Вы получили %d %s урона от вашего %s.");
f("PERIODICAURAHEALOTHEROTHER","%s gains %d health from %s's %s.","%s получил(а) %d здоровья от примененного %s - %s.");
f("PERIODICAURAHEALOTHERSELF","You gain %d health from %s's %s.","Вы получили %d здоровья от примененного %s - %s.");
f("PERIODICAURAHEALSELFOTHER","%s gains %d health from your %s.","%s получил(а) %d здоровья от вашего %s.");
f("PERIODICAURAHEALSELFSELF","You gain %d health from %s.","Вы получили %d здоровья от %s.");
f("RESIST_TRAILER"," (%d resisted)"," (%d отбито)");
f("SIMPLECASTOTHEROTHER","%s casts %s on %s.","%s применил(а) %s на %s.");
f("SIMPLECASTOTHERSELF","%s casts %s on you.","%s применил(а) %s на вас.");
f("SIMPLECASTSELFOTHER","You cast %s on %s.","Вы применили %s на %s.");
f("SIMPLECASTSELFSELF","You cast %s.","Вы применили %s.");
f("SIMPLEPERFORMOTHEROTHER","%s performs %s on %s.","%s применил(а) %s на %s.");
f("SIMPLEPERFORMOTHERSELF","%s performs %s on you.","%s применил(а) %s на вас.");
f("SIMPLEPERFORMSELFOTHER","You perform %s on %s.","Вы применили %s на %s.");
f("SIMPLEPERFORMSELFSELF","You perform %s.","Вы применили %s.");
f("SPELLCASTGOOTHER","%s casts %s.","%s сколдовал %s.");
f("SPELLCASTGOOTHERTARGETTED","%s casts %s on %s.","%s сколдовал %s на %s.");
f("SPELLCASTGOSELF","You cast %s.","Вы сколдовали %s.");
f("SPELLCASTGOSELFTARGETTED","You cast %s on %s.","Вы сколдовали %s на %s.");
f("SPELLCASTOTHERSTART","%s begins to cast %s.","%s начал колдовать %s.");
f("SPELLCASTSELFSTART","You begin to cast %s.","Вы начали колдовать %s.");
f("SPELLDEFLECTEDOTHEROTHER","%s's %s was deflected by %s.","%s применил %s и %s его отразил.");
f("SPELLDEFLECTEDOTHERSELF","%s's %s was deflected.","%s применил %s и вы его отразили.");
f("SPELLDEFLECTEDSELFOTHER","Your %s was deflected by %s.","Ваше %s отразил(а) %s.");
f("SPELLDEFLECTEDSELFSELF","You deflected your %s.","Вы уклонились от вашего %s.");
f("SPELLDISMISSPETOTHER","%s's %s is dismissed.","У %s питомец %s отпущен.");
f("SPELLDISMISSPETSELF","Your %s is dismissed.","Ваш питомец %s отпущен.");
f("SPELLDODGEDOTHEROTHER","%s's %s was dodged by %s.","%s применил %s и %s уклонился(ась).");
f("SPELLDODGEDOTHERSELF","%s's %s was dodged.","%s применил %s и вы уклонились.");
f("SPELLDODGEDSELFOTHER","Your %s was dodged by %s.","Вы применили %s и %s уклонился(ась).");
f("SPELLDODGEDSELFSELF","You dodged your %s.","Вы увернулись от вашего %s.");
f("SPELLDURABILITYDAMAGEALLOTHEROTHER","%s casts %s on %s: all items damaged.","%s сколдовал %s на %s: все вещи повреждены.");
f("SPELLDURABILITYDAMAGEALLOTHERSELF","%s casts %s on you: all items damaged.","%s сколдовал %s на вас: все вещи повреждены.");
f("SPELLDURABILITYDAMAGEALLSELFOTHER","You cast %s on %s: all items damaged.","Вы сколдовали %s на %s: все вещи повреждены.");
f("SPELLDURABILITYDAMAGEOTHEROTHER","%s casts %s on %s: %s damaged.","%s сколдовал %s на %s: %s повреждено.");
f("SPELLDURABILITYDAMAGEOTHERSELF","%s casts %s on you: %s damaged.","%s сколдовал %s на вас: %s повреждено.");
f("SPELLDURABILITYDAMAGESELFOTHER","You cast %s on %s: %s damaged.","Вы сколдовали %s на %s: %s повреждено.");
f("SPELLEVADEDOTHEROTHER","%s's %s was evaded by %s.","%s применил(а) %s и %s увернулся(ась).");
f("SPELLEVADEDOTHERSELF","%s's %s was evaded.","%s применил(а) %s и вы увернулись.");
f("SPELLEVADEDSELFOTHER","Your %s was evaded by %s.","Вы применили %s и %s увернулся(ась).");
f("SPELLEVADEDSELFSELF","You evaded your %s.","Вам удалось избежать своего %s.");
f("SPELLEXTRAATTACKSOTHER","%s gains %d extra attacks through %s.","%s получил %d дополнительных атак посредством %s.");
f("SPELLEXTRAATTACKSOTHER_SINGULAR","%s gains %d extra attack through %s.","%s получил %d дополнительную атаку посредством %s.");
f("SPELLEXTRAATTACKSSELF","You gain %d extra attacks through %s.","Вы получили %d дополнительных атак посредством %s.");
f("SPELLEXTRAATTACKSSELF_SINGULAR","You gain %d extra attack through %s.","Вы получили %d дополнительную атаку посредством %s.");
f("SPELLFAILCASTOTHER","%s fails to cast %s: %s.","%s неудачно сколдовал(а) %s: %s.");
f("SPELLFAILCASTSELF","You fail to cast %s: %s.","Вы неудачно сколдовали %s: %s.");
f("SPELLFAILPERFORMOTHER","%s fails to perform %s: %s.","%s неудачно выполнил(а) %s: %s.");
f("SPELLFAILPERFORMSELF","You fail to perform %s: %s.","Вы неудачно выполнили %s: %s.");
f("SPELLHAPPINESSDRAINOTHER","%s's %s loses %d happiness.","У %s %s потерял %d настроение.");
f("SPELLHAPPINESSDRAINSELF","Your %s loses %d happiness.","Ваш %s потерял %d настроение.");
f("SPELLIMMUNEOTHEROTHER","%s's %s fails. %s is immune.","%s неудачно выполнил %s. У %s иммунитет.");
f("SPELLIMMUNEOTHERSELF","%s's %s failed. You are immune.","%s неудачно выполнил %s. У вас иммунитет.");
f("SPELLIMMUNESELFOTHER","Your %s failed. %s is immune.","Ваше %s неудачно. У %s иммунитет.");
f("SPELLIMMUNESELFSELF","Your %s failed.  You are immune.","Ваш %s не удался. У вас иммунитет.");
f("SPELLINTERRUPTOTHEROTHER","%s interrupts %s's %s.","%s прервал примененное %s %s.");
f("SPELLINTERRUPTOTHERSELF","%s interrupts your %s.","%s прервал ваше %s.");
f("SPELLINTERRUPTSELFOTHER","You interrupt %s's %s.","Вы прервали примененное %s %s.");
f("SPELLLOGABSORBOTHEROTHER","%s's %s is absorbed by %s.","%s применил(а) %s и его поглотил(а) %s.");
f("SPELLLOGABSORBOTHERSELF","You absorb %s's %s.","Вы поглотили %s's %s.");
f("SPELLLOGABSORBSELFOTHER","Your %s is absorbed by %s.","Ваше %s поглотил(а) %s.");
f("SPELLLOGABSORBSELFSELF","You absorb your %s.","Вы поглотили ваше %s.");
f("SPELLLOGCRITOTHEROTHER","%s's %s crits %s for %d.","%s своим %s нанес %s критический урон %d.");
f("SPELLLOGCRITOTHERSELF","%s's %s crits you for %d.","%s своим %s нанес вам критический урон %d.");
f("SPELLLOGCRITSCHOOLOTHEROTHER","%s's %s crits %s for %d %s damage.","Персонаж %s нанёс заклинанием %s критический удар персонажу %s, нанеся %d %s урона.");
f("SPELLLOGCRITSCHOOLOTHERSELF","%s's %s crits you for %d %s damage.","Персонаж %s используя заклинание %s поразил вас критическим ударом, нанеся %d %s урона.");
f("SPELLLOGCRITSCHOOLSELFOTHER","Your %s crits %s for %d %s damage.","Ваше заклинание %s поразило персонажа %s, нанеся ему критический урон %d %s.");
f("SPELLLOGCRITSCHOOLSELFSELF","Your %s crits you for %d %s damage.","Ваше заклинание %s нанесло вам критический урон в %d %s очков.");
f("SPELLLOGCRITSELFOTHER","Your %s crits %s for %d.","Ваше %s нанесло %s критический урон %d.");
f("SPELLLOGCRITSELFSELF","Your %s crits you for %d.","Ваше %s нанесло вам критический урон %d.");
f("SPELLLOGOTHEROTHER","%s's %s hits %s for %d.","%s применил(а) %s и нанес(ла) %s урон %d.");
f("SPELLLOGOTHERSELF","%s's %s hits you for %d.","%s применил(а) %s и нанес(ла) вам урон %d.");
f("SPELLLOGSCHOOLOTHEROTHER","%s's %s hits %s for %d %s damage.","Персонаж %s используя заклинание %s поразил персонажа %s, нанеся ему %d %s урона.");
f("SPELLLOGSCHOOLOTHERSELF","%s's %s hits you for %d %s damage.","Персонаж %s используя заклинание %s поразил вас, нанеся %d %s урона.");
f("SPELLLOGSCHOOLSELFOTHER","Your %s hits %s for %d %s damage.","Ваше заклинание %s поразило персонажа %s и нанесла ему %d %s урона.");
f("SPELLLOGSCHOOLSELFSELF","Your %s hits you for %d %s damage.","Ваше заклинание %s поразило вас, и нанесло %d %s урона.");
f("SPELLLOGSELFOTHER","Your %s hits %s for %d.","Ваше %s нанесло %s урон %d.");
f("SPELLLOGSELFSELF","Your %s hits you for %d.","Ваше %s нанесло вам урон %d.");
f("SPELLMISSOTHEROTHER","%s's %s missed %s.","%s своим %s промахнулся(ась) по %s.");
f("SPELLMISSOTHERSELF","%s's %s misses you.","%s своим %s промахнулся(ась) по вам.");
f("SPELLMISSSELFOTHER","Your %s missed %s.","Ваше %s промазало по %s.");
f("SPELLMISSSELFSELF","Your %s misses you.","Ваш %s не попал по вам.");
f("SPELLPARRIEDOTHEROTHER","%s's %s was parried by %s.","%s выполнил(а) %s и был парирован %s.");
f("SPELLPARRIEDOTHERSELF","%s's %s was parried.","%s выполнил(а) %s и был парирован вами.");
f("SPELLPARRIEDSELFOTHER","Your %s is parried by %s.","Ваше %s парировано %s.");
f("SPELLPARRIEDSELFSELF","You parried your %s.","Вы отбили ваш %s.");
f("SPELLPERFORMGOOTHER","%s performs %s.","%s выполнил(а) %s.");
f("SPELLPERFORMGOOTHERTARGETTED","%s performs %s on %s.","%s применил(а) %s на %s.");
f("SPELLPERFORMGOSELF","You perform %s.","Вы применили %s.");
f("SPELLPERFORMGOSELFTARGETTED","You perform %s on %s.","Вы применили %s на %s.");
f("SPELLPERFORMOTHERSTART","%s begins to perform %s.","%s начал(а) выполнять %s.");
f("SPELLPERFORMSELFSTART","You begin to perform %s.","Вы начали выполнять %s.");
f("SPELLPOWERDRAINOTHEROTHER","%s's %s drains %d %s from %s.","Игрок %s используя %s вытянул %d %s из игрока %s.");
f("SPELLPOWERDRAINOTHERSELF","%s's %s drains %d %s from you.","Игрок %s используя %s вытянул %d %s из вас.");
f("SPELLPOWERDRAINSELFOTHER","Your %s drains %d %s from %s.","Ваше %s вытянуло %d %s из игрока %s.");
f("SPELLPOWERLEECHOTHEROTHER","%s's %s drains %d %s from %s. %s gains %d %s.","Игрок %s используя %s вытянул %d %s из игрока %s. %s получил %d %s.");
f("SPELLPOWERLEECHOTHERSELF","%s's %s drains %d %s from you. %s gains %d %s.","Игрок %s используя %s вытянул %d %s из вас. %s получил %d %s.");
f("SPELLPOWERLEECHSELFOTHER","Your %s drains %d %s from %s. You gain %d %s.","Ваше %s вытянуло %d %s из игрока %s. Вы получили %d %s.");
f("SPELLREFLECTOTHEROTHER","%s's %s is reflected back by %s.","%s применил(а) %s и оно было отражено %s.");
f("SPELLREFLECTOTHERSELF","You reflect %s's %s.","Вы отразили назад примененное %s %s.");
f("SPELLREFLECTSELFOTHER","Your %s is reflected back by %s.","Ваше %s отражено назад персонажем %s.");
f("SPELLREFLECTSELFSELF","You reflected your %s.","Вы отразили ваш %s.");
f("SPELLRESISTOTHEROTHER","%s's %s was resisted by %s.","%s применил(а) %s и не преодолел(а) стойкости %s.");
f("SPELLRESISTOTHERSELF","%s's %s was resisted.","%s применил(а) %s и не преодолел(а) вашей стойкости.");
f("SPELLRESISTSELFOTHER","Your %s was resisted by %s.","Ваше %s не преодолело стойкости %s.");
f("SPELLRESISTSELFSELF","You resisted your %s.","Вы стойки вашему %s.");
f("SPELLSPLITDAMAGEOTHEROTHER","%s's %s causes %s %d damage.","%s с помощью %s нанес(ла) %s урон %d.");
f("SPELLSPLITDAMAGEOTHERSELF","%s's %s causes you %d damage.","%s с помощью %s нанес(ла) вам урон %d.");
f("SPELLSPLITDAMAGESELFOTHER","Your %s causes %s %d damage.","Ваше %s нанесло %s урон %d.");
f("SPELLTEACHOTHEROTHER","%s teaches %s %s.","%s научил %s делать %s.");
f("SPELLTEACHOTHERSELF","%s teaches you %s.","%s научил вас делать %s.");
f("SPELLTEACHSELFOTHER","You teach %s %s.","Вы научили %s делать %s.");
f("SPELLTEACHSELFSELF","You teach yourself %s.","Вы выучили %s.");
f("SPELLTERSE_OTHER","%s casts %s.","%s колдует %s.");
f("SPELLTERSE_SELF","You cast %s.","Вы колдуете %s.");
f("SPELLTERSEPERFORM_OTHER","%s performs %s.","%s выполняет %s.");
f("SPELLTERSEPERFORM_SELF","You perform %s.","Вы выполняете %s.");
f("TRADESKILL_LOG_THIRDPERSON","%s creates %s.","%s создал(а) %s.");
f("UNITDESTROYEDOTHER","%s is destroyed.","%s разрушен.");
f("UNITDIESOTHER","%s dies.","%s умер.");
f("UNITDIESSELF","You die.","Вы умерли.");
f("UNKNOWNOBJECT","Unknown","Неизвестный объект");
f("VSABSORBOTHEROTHER","%s attacks. %s absorbs all the damage.","%s атаковал(а). %s поглотил(а) весь урон.");
f("VSABSORBOTHERSELF","%s attacks. You absorb all the damage.","%s атаковал(а). Вы поглотили весь урон.");
f("VSABSORBSELFOTHER","You attack. %s absorbs all the damage.","Вы атаковали. %s поглотил(а) весь урон.");
f("VSBLOCKOTHEROTHER","%s attacks. %s blocks.","%s атаковал(а). %s блокировал(а) атаку.");
f("VSBLOCKOTHERSELF","%s attacks. You block.","%s атаковал(а). Вы блокировали атаку.");
f("VSBLOCKSELFOTHER","You attack. %s blocks.","Вы атаковали. %s блокировал(а) атаку.");
f("VSDEFLECTOTHEROTHER","%s attacks. %s deflects.","%s атаковал(а). %s отразил(а) атаку.");
f("VSDEFLECTOTHERSELF","%s attacks. You deflect.","%s атаковал(а). Вы отразили атаку.");
f("VSDEFLECTSELFOTHER","You attack. %s deflects.","Вы атаковали. %s отразил(а) атаку.");
f("VSDODGEOTHEROTHER","%s attacks. %s dodges.","%s атаковал(а). %s уклонился(ась).");
f("VSDODGEOTHERSELF","%s attacks. You dodge.","%s атаковал(а). Вы уклонились.");
f("VSDODGESELFOTHER","You attack. %s dodges.","Вы атаковали. %s уклонился(ась).");
f("VSENVIRONMENTALDAMAGE_DROWNING_OTHER","%s is drowning and loses %d health.","%s тонет и потерял %d здоровья.");
f("VSENVIRONMENTALDAMAGE_DROWNING_SELF","You are drowning and lose %d health.","Вы тонете и потеряли %d здоровья.");
f("VSENVIRONMENTALDAMAGE_FALLING_OTHER","%s falls and loses %d health.","%s упал(а) и потерял %d здоровья.");
f("VSENVIRONMENTALDAMAGE_FALLING_SELF","You fall and lose %d health.","Вы упали и потеряли %d здоровья.");
f("VSENVIRONMENTALDAMAGE_FATIGUE_OTHER","%s is exhausted and loses %d health.","%s выдохлись и потеряли %d здоровья.");
f("VSENVIRONMENTALDAMAGE_FATIGUE_SELF","You are exhausted and lose %d health.","Вы выдохлись и потеряли %d здоровья.");
f("VSENVIRONMENTALDAMAGE_FIRE_OTHER","%s suffers %d points of fire damage.","%s получил(а) урон %d от огня.");
f("VSENVIRONMENTALDAMAGE_FIRE_SELF","You suffer %d points of fire damage.","Вы получили урон %d от огня.");
f("VSENVIRONMENTALDAMAGE_LAVA_OTHER","%s loses %d health for swimming in lava.","%s потерял(а) %d здоровья во время плавания в лаве.");
f("VSENVIRONMENTALDAMAGE_LAVA_SELF","You lose %d health for swimming in lava.","Вы потеряли %d здоровья во время плавания в лаве.");
f("VSENVIRONMENTALDAMAGE_SLIME_OTHER","%s loses %d health for swimming in slime.","%s потерял(а) %d здоровья во время плавания в слизи.");
f("VSENVIRONMENTALDAMAGE_SLIME_SELF","You lose %d health for swimming in slime.","Вы потеряли %d здоровья во время плавания в слизи.");
f("VSEVADEOTHEROTHER","%s attacks. %s evades.","%s атаковал(а). %s увернулся(ась).");
f("VSEVADEOTHERSELF","%s attacks. You evade.","%s атаковал(а). Вы увернулись.");
f("VSEVADESELFOTHER","You attack. %s evades.","Вы атаковали. %s увернулся(ась).");
f("VSIMMUNEOTHEROTHER","%s attacks but %s is immune.","%s атаковал(а), но у %s иммунитет.");
f("VSIMMUNEOTHERSELF","%s attacks but you are immune.","%s атаковал(а), но у вас иммунитет.");
f("VSIMMUNESELFOTHER","You attack but %s is immune.","Вы атаковали, но у %s иммунитет.");
f("VSPARRYOTHEROTHER","%s attacks. %s parries.","%s атаковал(а). %s парировал(а) атаку.");
f("VSPARRYOTHERSELF","%s attacks. You parry.","%s атаковал(а). Вы парировали атаку.");
f("VSPARRYSELFOTHER","You attack. %s parries.","Вы атаковали. %s парировал(а) атаку.");
f("VSRESISTOTHEROTHER","%s attacks. %s resists all the damage.","%s атаковал. %s стоек к нанесённому урону.");
f("VSRESISTOTHERSELF","%s attacks. You resist all the damage.","%s атаковал. Вы стойки к нанесённому урону.");
f("VSRESISTSELFOTHER","You attack. %s resists all the damage.","Вы атаковали. %s стоек к нанесённому урону.");
f("VULNERABLE_TRAILER"," (+%d vulnerability bonus)"," (+%d бонус уязвимости)\"; -- Appended to attack strings in the combat log when damage is amplified by vulnerability. (NOTE SPACE AT BEGINNING) WAISTSLOT = \"Пояс");
end
